### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by rajadain** [TheAcademyofNaturalSciences/BMPxlsx#1]
We're upgrading MMW to Python 3 in https://github.com/WikiWatershed/model-my-watershed/issues/3165, and require the libraries we use to have Python 3 versions as well.

Could this library be upgraded to Python 3 and released as a new major version to PyPI please?

**Comment by mikecampagna** [comment]
Hi Terence, the library has been updated and I have verified it passing for Python 3.7. The build should be valid for Python >= 3.6 but let me know if you have any issues.

**Comment by rajadain** [comment]
Works great, thank you!!
